name: "Portainer"
description: "Manage your Docker environment with ease"
url: https://github.com/shortsn/hassio-addons/portainer
version: "dev"
slug: portainer
init: false
advanced: true
ingress: true
ingress_stream: true
hassio_api: true
docker_api: true

startup: services
panel_icon: mdi:docker
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
ports:
  8000/tcp: null
ports_description:
  8000/tcp: Edge Agent Api (Enable when managing remote edge agents)
  
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  agent_secret": "str?"
