name: "MQTT Inpsect"
description: "Inspect MQTT Messages"
url: https://github.com/shortsn/hassio-addons/tree/main/mqtt-inspect
version: "dev"
slug: "mqtt_inspect"
startup: application
services:
  - mqtt:need
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
