name: "MQTT Inpsect"
description: "Inspect MQTT Messaged"
url: https://github.com/shortsn/hassio-addons/mqtt-inspect
version: "dev"
slug: "mqtt_inspect"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
